spring.application.name=Aula-05.05.2026

spring.datasource.url=jdbc:mysql://localhost:3306/api_0605
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
