spring.application.name=revisao

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_gf
spring.datasource.username=root
spring.datasource.password=

