spring.application.name=revisao22042026

# URL de conexão com o banco que você criou no Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/teste1

# Usuário padrão do MySQL
spring.datasource.username=root

# A senha do seu MySQL (SUBSTITUA AQUI PELA SUA SENHA REAL!)
spring.datasource.password=88545135

# Informa qual é o driver que fará a conexão
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Faz com que o Spring crie as tabelas no banco automaticamente se necessário
spring.jpa.hibernate.ddl-auto=update

