spring.application.name=Aula15042026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/aula15042026
spring.datasource.username=root
spring.datasource.password=